### PR TITLE
added Contributing.md folder

### PR DESCRIPTION
**Pull request by yuvicc**
#7

### CODE REVIEW

**Review by cyai — COMMENTED** [review]
Thank you for this contributing.md file. But don't you think this is very intensive? Could you remove the tutorials for how to commit and working with `git`? Let's keep it short and brief!

**Comment by yuvicc** [comment]
> Thank you for this contributing.md file. But don't you think this is very intensive? Could you remove the tutorials for how to commit and working with `git`? Let's keep it short and brief!

I have updated, can you review it

**Comment by cyai** [comment]
Looks good! Approving for changes.

**Review by cyai — APPROVED** [review]
Looks good! Approving for changes.

**Pull request merged**
